jobs:
  include:
    - language: python
      python: 3.7
      before_install:
        - cd backend/graminsta
      install:
        - pip install -r requirements.txt
      script:
        - python -m flake8
        - find . -type d -maxdepth 2 -not -path '.' -not -path 'graminsta' | xargs python -m pylint
    - language: dart
      dart: stable
      dart_task:
        - dartanalyzer: --fatal-warnings lib
    - language: dart
      dart: stable
      dart_task:
        - dartfmt
