language: python
python:
  - "3.7"
before_install:
  - cd backend/graminsta
install:
  - pip install -r requirements.txt
script:
  - python -m flake8
  - find . -type d -maxdepth 1 | xargs python -m pylint
