jobs:
  include:
    - language: python
      python: 3.7
      before_install:
        - cd backend/graminsta
      install:
        - pip install -r requirements.txt
      script:
        - python -m flake8
        - find . -type d -maxdepth 2 -not -path '.' -not -path 'graminsta' | xargs python -m pylint
    - language: dart
      dart: stable
      addons:
        apt:
          packages:
            - lib32stdc++6
      install:
        - git clone https://github.com/flutter/flutter.git -b stable sdk
        - $HOME/sdk/flutter/bin/flutter doctor
      dart_task:
        dartfmt: True
        dartanalyzer: --fatal-warnings flutter/Graminsta
      cache:
        directories:
          - $HOME/.pub-cache

